name: Deploy txt2img

on:
  workflow_dispatch:
  push:
    branches: [ "release" ]

env:
  EC2_USER: ubuntu
  EC2_HOST: ec2-43-202-225-47.ap-northeast-2.compute.amazonaws.com
  EC2_DIR: /home/ubuntu/txt2img
  SSH_KEY_PATH: ~/.ssh/ten_color.pem
  DEPLOY_SH: deploy_txt2img.sh

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production  # 指定 Environment

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install SSH client
      run: sudo apt-get update && sudo apt-get install -y ssh rsync

    - name: Save SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.TEM_COLOR_PEM }}" > ${{ env.SSH_KEY_PATH }}
        chmod 600 ${{ env.SSH_KEY_PATH }}

    - name: Upload project files to EC2
      run: |
        rsync -avz --delete --exclude='.git' -e "ssh -o StrictHostKeyChecking=no -i ${{ env.SSH_KEY_PATH }}" \
        ./ ${{ env.EC2_USER }}@${{ env.EC2_HOST }}:${{ env.EC2_DIR }}/

    - name: SSH and run deploy script
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ env.SSH_KEY_PATH }} \
        ${{ env.EC2_USER }}@${{ env.EC2_HOST }} \
        "cd ${{ env.EC2_DIR }} && chmod +x ${{ env.DEPLOY_SH }} && ./${{ env.DEPLOY_SH }}"
